---
title: "task1"
author: "許煌浚"
date: "2019/7/11"
output: html_document
---

```{r setup, include=FALSE}
library(stats)
library(base)
library(dplyr)
library(ggplot2)
library(ggfortify)
filename1 <- "unemployment rate.csv"
data1<-read.csv(filename1)
filename2 <- "suicide.csv"
data2<-read.csv(filename2)
data5<-aggregate(data2$suicides_num, by=list(Category=data2$year), FUN=sum)/aggregate(data2$population, by=list(Category=data2$year), FUN=sum)
data1
final<-data1%>%mutate(suicide_rate=data5$x)
colnames(final)=c("year","Unemployment_Rate","GDP","Inflation","suicide_rate")
colnames(final)=c("year","Unemployment_Rate","GDP","Inflation","suicide_rate")
```

# US SuicideRate,GDP,UnemploymentRate,inflation by years (1979-2015)

```{r}
knitr::kable(final, format="html")
```

# US Annual SuicideRate (1979-2015)

```{r}
ggplot(data = final, aes(x = year, y=suicide_rate)) +
  geom_point()
```  
  
# US Annual SuicideRate versus UnemploymentRate (1979-2015)
  
```{r}
final %>%
  ggplot(aes(x=Unemployment_Rate, y=suicide_rate)) +
  geom_point(aes(col=Unemployment_Rate), position=position_jitter(width=.05)) +
  geom_smooth(method='lm',formula=y~x, se=F)+theme(axis.text.x= element_text(size=10, family="myFont", color="black", face= "bold", vjust=0.5, hjust=0.5))
sprintf("Correlation Coefficient=%.4f",cor(final$Unemployment_Rate,final$suicide_rate))
```

